id: atek.cloud/service
type: adb-record
title: Service
description: Service installed to a host environment.
templates:
  table:
    title: Services
    description: Services installed to the host environment.
  record:
    key:
      - type: json-pointer
        value: "/id"
    title:
      - type: string
        value: "Service \""
      - type: json-pointer
        value: "/id"
      - type: string
        value: "\", source: "
      - type: json-pointer
        value: "/sourceUrl"
definition:
  type: object
  required: ["id", "port", "sourceUrl", "package", "system", "installedBy"]
  properties:
    id:
      type: string
      pattern: "^([a-zA-Z][a-zA-Z0-9-]{1,62}[a-zA-Z0-9])$"
    port:
      type: number
    sourceUrl: 
      type: string
      format: uri
    desiredVersion:
      type: string
    package:
      type: object
      required: ["sourceType"]
      properties:
        sourceType:
          type: string
          enum: ["file", "git"]
        installedVersion:
          type: string
        title:
          type: string
    manifest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        author:
          type: string
        license:
          type: string
    system:
      type: object
      required: ["appPort"]
      properties:
        appPort:
          type: number
    installedBy:
      type: string
      pattern: "^([a-zA-Z][a-zA-Z0-9-]{1,62}[a-zA-Z0-9])$"